[pytest]
filterwarnings =
    ignore::pytest.PytestAssertRewriteWarning
addopts =
    -p no:faulthandler
    -p no:playwright
    -s
    --cache-clear
    --capture=sys
    --tracing=off
    --screenshot=on
    --video=retain-on-failure
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
markers =
    login: 登录测试用例
    system_manager: 系统管理测试用例


log_cli = False