[pytest]
filterwarnings =
    ignore::pytest.PytestAssertRewriteWarning
addopts =
    -p no:faulthandler
    -p no:playwright
    -s
    --cache-clear
    --capture=sys
    --tracing=off
    --screenshot=on
    --video=retain-on-failure
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
markers =
    sys: 系统管理测试用例
    cbb: CBB测试用例
    apidesign: CBB接口设计测试用例
    document: 文档相关测试用例


log_cli = False